Playable on mobile
evelynstender/skateboard-game pull request #2
Opened 2021-01-01 18:11 UTC by angeloevangelista

Hey Evelyn!

I found your post and I enjoyed a lot your game, I loved the flying scooter 🤣🤣. So, I'm proposing some improves.
Since I saw your post at my cellphone, I couldn't play it. In order that, here are some things that makes it possible now.

[x] Fixing `width` to use 100% and `700px` as maximum, since You've chosen that.
[x] Using `calc` in css to define left property instead the pixel value, it prevents some scooters and rocks flying away from the screen :p.
[x] Adding buttons, 'cause I think You, just like me, don't use a keyboard in your cellphone 🤔 

I hope it could be useful for You 😉

2021-01-03 15:53 UTC, evelynstender requested changes

2021-01-03 15:53 UTC, evelynstender commented on src/components/Game/Game.vue
> +      <button name="up-button" type="button">UP</button>
I think it would be cool to hide those buttons when you're playing on a desktop, so the page looks more clear. What do you think?

2021-01-03 15:53 UTC, evelynstender commented on src/components/Game/Game.vue
> +    buttonDown() {
I noticed when you press the down button, the skater stays don't and never goes back to the standing position. I'm not sure if this is an actual issue, but I think it would be nice to somehow make the skater get back to the standing position?

2021-01-03 15:54 UTC, evelynstender commented
Also, I thought about removing the flying scooter on the mobile version to avoid certain issues. And instead of having a "UP" button, the user could just tap the screen to ollie.

2021-01-04 01:20 UTC, angeloevangelista commented on src/components/Game/Game.vue
> +      <button name="up-button" type="button">UP</button>
It makes sense, I'll do it.

2021-01-04 01:22 UTC, angeloevangelista commented on src/components/Game/Game.vue
> +    buttonDown() {
Yes, I agree. It's not a real problem, but can be a little strange.

2021-01-04 01:31 UTC, angeloevangelista commented
> Also, I thought about removing the flying scooter on the mobile version to avoid certain issues. And instead of having a "UP" button, the user could just tap the screen to ollie.

I think it's a good idea, the scooters are the only reason to crouch the (radical) guy, so removing this, as You told, a 'tap' on the screen it's the only control necessary. 🤔

I will find a way to disable the scooter while on mobile. Should I create a new PR for that?

2021-01-04 07:20 UTC, evelynstender commented
> > Also, I thought about removing the flying scooter on the mobile version to avoid certain issues. And instead of having a "UP" button, the user could just tap the screen to ollie.
> 
> I think it's a good idea, the scooters are the only reason to crouch the (radical) guy, so removing this, as You told, a 'tap' on the screen it's the only control necessary. 🤔
> 
> I will find a way to disable the scooter while on mobile. Should I create a new PR for that?

That would be great!!

2021-01-04 21:23 UTC, angeloevangelista reviewed
Well, I think it's better now. Please take a look and tell me what you think

2021-01-04 21:23 UTC, angeloevangelista commented on src/components/Game/Game.vue
> +
And now We have this conditional to check if it is running on a mobile device or not

2021-01-04 21:23 UTC, angeloevangelista commented on src/components/Game/Game.vue
> -    </div>
The buttons were removed from here...

2021-01-04 21:23 UTC, angeloevangelista commented on src/components/Game/Game.vue
> -      this.skaterDown = false;
I kept this in a method, even being only a function 'cause I think it makes sense, since it's being referenced in more than one place and can be modified in future to include new things

2021-01-04 21:23 UTC, angeloevangelista commented on src/components/Game/Game.vue
> +      !this.runningOnMobile && setTimeout(() => {
🛴 

Adding scooters only when not in mobile

2021-01-09 09:06 UTC, evelynstender approved these changes

2021-01-09 09:07 UTC, evelynstender commented
Nice one @angeloevangelista! I'm merging this PR now!

2021-01-09 09:07 UTC, merged